// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "e6d814a7-59c0-4cf8-8622-54fdb877058f");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1612931459);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1612931579);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1612959720);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1612959840);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1612931219);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1612931339);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1612931819);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1612931699);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1612242529);
user_pref("browser.laterrun.bookkeeping.sessionCount", 15);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 78);
user_pref("browser.newtabpage.activity-stream.impressionId", "{1f784232-931a-44a6-9445-c5e79a0ace11}");
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1612377000);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 1);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1612961481043");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1612963296043");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1612959705609");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1612981305609");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190327091201");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1612959694");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20190327091201");
user_pref("browser.startup.homepage_override.mstone", "66.0.2");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1612242554347");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "66.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("extensions.blocklist.lastModified", "Sun, 07 Feb 2021 02:33:01 GMT");
user_pref("extensions.blocklist.pingCountTotal", 6);
user_pref("extensions.blocklist.pingCountVersion", 6);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1612931461);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190327091201");
user_pref("extensions.lastAppVersion", "66.0.2");
user_pref("extensions.lastPlatformVersion", "66.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"88739f63-846f-470e-91c7-137e5dc25187\",\"screenshots@mozilla.org\":\"639b4041-d0a9-45e5-b35b-8e48d7fd9e99\",\"webcompat-reporter@mozilla.org\":\"0f51cbfd-d31d-4d2f-9f87-97369e30ed62\",\"webcompat@mozilla.org\":\"735f49f2-99bd-4144-aafe-a8d360bdb5ea\",\"baidu-code-update@mozillaonline.com\":\"2bd63e6a-c4ec-4f80-b0f9-b45e7e7f31a0\",\"fxmonitor@mozilla.org\":\"899146e2-79ff-4117-a032-51e4b10e67f4\"}");
user_pref("idle.lastDailyNotification", 1612931201);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1612415374);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190327091201");
user_pref("media.gmp-manager.lastCheck", 1612931043);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1612931201);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "a145ca40-e046-40fb-9943-a6ab61e65f88");
user_pref("security.sandbox.plugin.tempDirSuffix", "0cc73fa7-bcc1-4236-98f4-80b123aba523");
user_pref("services.blocklist.addons.checked", 1612931340);
user_pref("services.blocklist.gfx.checked", 1612931340);
user_pref("services.blocklist.onecrl.checked", 1612931340);
user_pref("services.blocklist.pinning.checked", 1612931340);
user_pref("services.blocklist.plugins.checked", 1612931340);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_update_seconds", 1612931340);
user_pref("services.settings.main.language-dictionaries.last_check", 1612931340);
user_pref("services.settings.main.sites-classification.last_check", 1612931340);
user_pref("services.settings.main.tippytop.last_check", 1612931340);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1612275540);
user_pref("toolkit.startup.last_success", 1612959685);
user_pref("toolkit.telemetry.cachedClientID", "fae64f3a-dc71-4239-8172-ded88c1162cd");
user_pref("toolkit.telemetry.previousBuildID", "20190327091201");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
